apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
      - name: production
        imagePullPolicy: Always
        image: sorix6/capstone-project
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate