apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::505488625686:role/capstone-project-worker-nodes-NodeInstanceRole-HF6SL3EMN1LH
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::505488625686:user/eks-jenkins
      username: eks-jenkins
      groups:
      - system:masters